(cl:defpackage openrobot_vesc_msgs-msg
  (:use )
  (:export
   "<VESCGETCUSTOMAPP>"
   "VESCGETCUSTOMAPP"
   "<VESCSETCOMMAND>"
   "VESCSETCOMMAND"
   "<VESCSETCUSTOMAPP>"
   "VESCSETCUSTOMAPP"
   "<VESCSTATE>"
   "VESCSTATE"
   "<VESCSTATESTAMPED>"
   "VESCSTATESTAMPED"
  ))

